 
substitutions:
  friendly_name: Zehnder ComfoAir Q
  device_name: zehnder-comfoair-q # max 24 chars
  device_description: Zehnder ComfoAir Q HRV (heat recovery ventilation) unit
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

  
esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-zehnder-comfoair
    version: "2024.8.0"

# Enable Home Assistant API
api:
    encryption:
      key: !secret api_encryption_key
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password
    ssid: "$device_name Hotspot"

external_components: 
  - source: github://yoziru/esphome-zehnder-comfoair/components@main
    components: [ zehnder_comfoair_q ]

packages:
  base: !include packages/new_base.yml
  device_base: !include boards/m5stack-atoms3.yml